// <auto-generated />
using System.Collections.Generic;
using DisasterResourceAllocation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DisasterResourceAllocation.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DisasterResourceAllocation.Models.Area", b =>
                {
                    b.Property<string>("AreaID")
                        .HasColumnType("text")
                        .HasColumnName("area_id")
                        .HasAnnotation("Relational:JsonPropertyName", "AreaID");

                    b.Property<Dictionary<string, int>>("RequiredResources")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("required_resources")
                        .HasAnnotation("Relational:JsonPropertyName", "RequiredResources");

                    b.Property<int>("TimeConstraint")
                        .HasColumnType("integer")
                        .HasColumnName("time_constraint")
                        .HasAnnotation("Relational:JsonPropertyName", "TimeConstraint");

                    b.Property<int>("UrgencyLevel")
                        .HasColumnType("integer")
                        .HasColumnName("urgency_level")
                        .HasAnnotation("Relational:JsonPropertyName", "UrgencyLevel");

                    b.HasKey("AreaID");

                    b.ToTable("areas");
                });

            modelBuilder.Entity("DisasterResourceAllocation.Models.Truck", b =>
                {
                    b.Property<string>("TruckID")
                        .HasColumnType("text")
                        .HasColumnName("truck_id")
                        .HasAnnotation("Relational:JsonPropertyName", "TruckID");

                    b.Property<Dictionary<string, int>>("AvailableResources")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("available_resources")
                        .HasAnnotation("Relational:JsonPropertyName", "AvailableResources");

                    b.Property<Dictionary<string, int>>("TravelTimeToArea")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("travel_time_to_area")
                        .HasAnnotation("Relational:JsonPropertyName", "TravelTimeToArea");

                    b.HasKey("TruckID");

                    b.ToTable("trucks");
                });
#pragma warning restore 612, 618
        }
    }
}
